server:
  port: 8003
mybatis:
  type-aliases-package: com.navinfo.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    # 3个服务名称一致是前提
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://10.130.11.246:3306/sap-service-bak?useUnicode=true&characterEncoding=utf8
    username: root
    password: fm_mysql123456

# Eureka配置：配置服务注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  #修改Eureka上的默认描述信息
  instance:
    instance-id: springcloud-provider-dept8003

#info配置
info:
  app.name: zzw-cloud
  company.name: 四维图新